PRAGMA encoding="UTF-8";

CREATE TABLE IF NOT EXISTS facts (
    id INTEGER PRIMARY KEY,
    thing TEXT NOT NULL COLLATE NOCASE,
    fact TEXT NOT NULL COLLATE NOCASE,
    inactive BOOLEAN NOT NULL DEFAULT FALSE,
    UNIQUE (thing, fact)
);

CREATE TABLE IF NOT EXISTS karma (
    id INTEGER PRIMARY KEY,
    thing TEXT NOT NULL COLLATE NOCASE UNIQUE,
    value integer DEFAULT 0 NOT NULL
);
